// Beau Papier — data loading + reusable render helpers
window.DearDaria = window.DearDaria || {};

DearDaria.loadData = async function () {
  if (DearDaria._data) return DearDaria._data;
  const res = await fetch('site-data.json');
  const data = await res.json();
  DearDaria._data = data;
  return data;
};

// Optimised WebP copies live in img/ (large) and img/sm/ (small), generated by
// tools/optimize_images.py from the untouched originals in clean_images/.
DearDaria.imgBase = function (filename) {
  return String(filename || '').replace(/\.(jpe?g|png)$/i, '');
};
DearDaria.imgUrl = function (filename) {
  return `img/${DearDaria.imgBase(filename)}.webp`;
};
DearDaria.imgUrlSmall = function (filename) {
  return `img/sm/${DearDaria.imgBase(filename)}.webp`;
};

// Safety net: if an optimised copy is missing (e.g. a new photo was added
// without running the optimiser), silently fall back to the original photo.
(function () {
  const EXT = ['.jpg', '.jpeg', '.png'];
  document.addEventListener('error', function (e) {
    const img = e.target;
    if (!img || img.tagName !== 'IMG') return;
    const m = (img.getAttribute('src') || '').match(/^img\/(?:sm\/)?(.+)\.webp$/);
    const step = Number(img.dataset.fallbackStep || 0);
    const base = m ? m[1] : img.dataset.fallbackBase;
    if (!base || step >= EXT.length) return;
    img.dataset.fallbackBase = base;
    img.dataset.fallbackStep = step + 1;
    img.src = `clean_images/${base}${EXT[step]}`;
  }, true);
})();

// Descriptive photo text (alt text): invisible on the page, read by Google
// Images and screen readers. Kept natural - one clear sentence per photo.
DearDaria.ALT_TYPE = {
  fr: {
    bundle: 'Suite de papeterie de mariage', sleeve: 'Faire-part de mariage avec pochette',
    jacket: 'Faire-part de mariage avec habillage', place_card: 'Marque-place de mariage',
    rsvp: 'Carte-réponse de mariage', save_the_date: 'Save the date, carte d\u2019annonce de mariage',
    menu: 'Menu de mariage', glass_tag: 'Étiquette à verre de mariage',
    envelope_liner: 'Doublure d\u2019enveloppe de faire-part', details_card: 'Carte de déroulement de mariage',
    other: 'Faire-part de mariage', _: 'Papeterie de mariage',
  },
  en: {
    bundle: 'Wedding stationery suite', sleeve: 'Wedding invitation with sleeve',
    jacket: 'Wedding invitation with jacket', place_card: 'Wedding place card',
    rsvp: 'Wedding RSVP card', save_the_date: 'Wedding save the date card',
    menu: 'Wedding menu', glass_tag: 'Wedding glass tag',
    envelope_liner: 'Wedding envelope liner', details_card: 'Wedding details card',
    other: 'Wedding invitation', _: 'Wedding stationery',
  },
  de: {
    bundle: 'Hochzeitspapeterie-Set', sleeve: 'Hochzeitseinladung mit Hülle',
    jacket: 'Hochzeitseinladung mit Umschlag', place_card: 'Platzkarte für die Hochzeit',
    rsvp: 'Antwortkarte für die Hochzeit', save_the_date: 'Save-the-Date-Karte zur Hochzeit',
    menu: 'Hochzeitsmenü', glass_tag: 'Glasanhänger für die Hochzeit',
    envelope_liner: 'Umschlagfutter für Hochzeitseinladungen', details_card: 'Ablaufkarte für die Hochzeit',
    other: 'Hochzeitseinladung', _: 'Hochzeitspapeterie',
  },
};
DearDaria.ALT_SUFFIX = {
  fr: 'papeterie de mariage découpée, imaginée et réalisée en Suisse par Beau Papier',
  en: 'cut-paper wedding stationery designed and made in Switzerland by Beau Papier',
  de: 'ausgeschnittene Hochzeitspapeterie, entworfen und gefertigt in der Schweiz von Beau Papier',
};
DearDaria.altSuffix = function () {
  return DearDaria.ALT_SUFFIX[DearDaria.getLang()] || DearDaria.ALT_SUFFIX.fr;
};
DearDaria.seoAlt = function (collection, type) {
  const map = DearDaria.ALT_TYPE[DearDaria.getLang()] || DearDaria.ALT_TYPE.fr;
  const kind = (type && map[type]) || map._;
  const name = collection ? DearDaria.collectionDisplayName(collection) : '';
  const text = `${kind}${name ? ' ' + name : ''} \u2013 ${DearDaria.altSuffix()}`;
  return text.replace(/"/g, '&quot;');
};

DearDaria.formatPrice = function (price) {
  if (price === null || price === undefined) return null;
  return `CHF ${Number(price).toFixed(2)}`;
};

DearDaria.PRODUCT_TYPE_KEY = {
  bundle: 'label_bundle',
  sleeve: 'label_sleeve',
  jacket: 'label_jacket',
  place_card: 'label_place_card',
  rsvp: 'label_rsvp',
  save_the_date: 'label_save_the_date',
  menu: 'label_menu',
  glass_tag: 'label_glass_tag',
  envelope_liner: 'label_envelope_liner',
  details_card: 'label_details_card',
  other: 'label_other',
};

DearDaria.productTypeLabel = function (type) {
  const key = DearDaria.PRODUCT_TYPE_KEY[type] || 'label_other';
  return DearDaria.t(key);
};

DearDaria.PERSONALISABLE_TYPES = ['sleeve', 'jacket', 'bundle', 'other'];

// collection.name is still the internal working label (e.g. "Calla Lily",
// "Boho Peony") - never touched by the French naming pass. Derive a clean
// French family name from whichever real product title we have, by
// stripping the known type-prefix ("Suite ", "Faire-part ", etc.).
const TYPE_PREFIXES = [
  'Suite de Mariage ', 'Suite ', 'Faire-part ', 'Menu ', 'Marque-place ',
  'Carte-r\u00e9ponse ', 'Carte d\u2019annonce ', 'Doublure d\u2019enveloppe ',
  'Pi\u00e8ce coordonn\u00e9e ', '\u00c9tiquette \u00e0 Verre ',
];
DearDaria.collectionDisplayName = function (collection) {
  const lang = DearDaria.getLang();
  if (collection.display_name) {
    return collection.display_name[lang] || collection.display_name.fr || collection.name;
  }
  // fallback for any collection missing the field (shouldn't happen, but never break)
  const preferred = collection.products.find(p => p.type === 'bundle')
    || collection.products.find(p => p.type === 'sleeve' || p.type === 'other')
    || collection.products[0];
  return (preferred && (preferred.title_fr || preferred.title)) || collection.name;
};

DearDaria.productTitle = function (product) {
  const lang = DearDaria.getLang();
  return product['title_' + lang] || product.title_fr || product.title || '';
};

DearDaria.collectionDescription = function (collection) {
  const lang = DearDaria.getLang();
  if (collection.description && typeof collection.description === 'object') {
    return collection.description[lang] || collection.description.fr || collection.description.en || '';
  }
  return collection.description || '';
};

// Renders a collection card: clean image, no prices, "Découvrir ce modèle" CTA language.
DearDaria.collectionCardHTML = function (collection) {
  const anyPersonalisable = collection.products.some(p => DearDaria.PERSONALISABLE_TYPES.includes(p.type));
  const badge = anyPersonalisable ? `<span class="badge-personalisable">${DearDaria.t('personalisable_badge')}</span>` : '';
  return `
    <a class="card" href="collection.html?slug=${collection.slug}">
      <div class="card-media">
        <img class="lazy-img" loading="lazy" src="${DearDaria.imgUrlSmall(collection.hero)}" alt="${DearDaria.seoAlt(collection)}">
        <div class="card-hover-caption">
          <div class="unfold-rule"></div>
          <div class="name">${collection.name}</div>
          <div class="view">${DearDaria.t('discover_model')}</div>
        </div>
      </div>
      <div class="card-caption-static design-card-meta">
        <div class="name">${collection.name}</div>
        <div class="type-row">${badge}</div>
      </div>
    </a>`;
};

DearDaria.productCardHTML = function (collection, product, image) {
  const label = DearDaria.productTypeLabel(product.type);
  const title = DearDaria.productTitle(product);
  const badge = DearDaria.PERSONALISABLE_TYPES.includes(product.type) ? `<span class="badge-personalisable">${DearDaria.t('personalisable_badge')}</span>` : '';
  const url = `product.html?slug=${collection.slug}&type=${product.type}`;
  const heartId = `${collection.slug}__${product.type}`;
  const heart = DearDaria.heartButtonHTML ? DearDaria.heartButtonHTML({ id: heartId, title, image, url, type: label }) : '';
  return `
    <a class="card" href="${url}">
      <div class="card-media">
        <img class="lazy-img" loading="lazy" src="${DearDaria.imgUrlSmall(image)}" alt="${DearDaria.seoAlt(collection, product.type)}">
        ${heart}
        <div class="card-hover-caption">
          <div class="unfold-rule"></div>
          <div class="name">${title}</div>
          <div class="view">${DearDaria.t('discover_model')}</div>
        </div>
      </div>
      <div class="card-caption-static design-card-meta">
        <div class="name">${title}</div>
        <div class="type-row"><span class="type">${label}</span>${badge}</div>
      </div>
    </a>`;
};

DearDaria.renderGrid = function (mountId, html, cols) {
  const mount = document.getElementById(mountId);
  if (!mount) return;
  mount.className = `grid cols-${cols || 3}`;
  mount.innerHTML = html;
  if (DearDaria.initLazyImages) DearDaria.initLazyImages();
};

DearDaria.getQueryParam = function (key) {
  return new URLSearchParams(window.location.search).get(key);
};
